### ISSUE TITLE
emailing log file - error, help please

### ISSUE THREAD

**Issue by chrisbwy** [christianspecht/scm-backup#23]
Hi - I'm getting an error when trying to email the log file.

Settings...

email:
  from: app@arris.com
  to: chris.hargreaves@arris.com
  server: smtp.arrisi.com
  port: 25
  useSsl: false
  userName:
  password:

Log Message...

Backup finished!
The backups are in this directory: c:\scm-backup\

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: userName
   at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken)
   at ScmBackup.Http.MailKitEmailSender.Send(String subject, String body) in C:\projects\scm-backup\src\ScmBackup\Http\MailKitEmailSender.cs
:line 17
   at ScmBackup.LogMailingScmBackup.Run() in C:\projects\scm-backup\src\ScmBackup\LogMailingScmBackup.cs:line 31
   at ScmBackup.Program.Main(String[] args) in C:\projects\scm-backup\src\ScmBackup\Program.cs:line 9

Note our server does not require a userName or password.

Any ideas what the problem is?

Many thanks in advance.

Regards

Chris

**Comment by christianspecht** [comment]
Unfortunately I don't have access to a SMTP server which doesn't require authentication.
So I can only try some stuff, and I need you to check whether it helped.

Can you try this version?
https://ci.appveyor.com/project/ChristianSpecht/scm-backup/builds/19385148/artifacts

**Comment by christianspecht** [comment]
No, this shouldn't happen with the default settings.

I didn't notice it because I only tested the mails with a GitHub account *(where I'm using GitHub's Octokit library, which doesn't log)*, but not with a Bitbucket account *(where I'm calling the API in my own code, **with** full logging)*.

I just pushed another change - please try this version:
https://ci.appveyor.com/project/ChristianSpecht/scm-backup/builds/19444335/artifacts

**Comment by plbrownoptivcom** [comment]
Would it be possible to add the config option to connect to an internal BB instance?

Paul Brown | 913.526.0939

On Oct 11, 2018, at 3:37 PM, Christian Specht <notifications@github.com<mailto:notifications@github.com>> wrote:

[External Email]
________________________________

No, this shouldn't happen with the default settings.

I didn't notice it because I only tested the mails with a GitHub account (where I'm using GitHub's Octokit library, which doesn't log), but not with a Bitbucket account (where I'm calling the API in my own code, with full logging).

I just pushed another change - please try this version:
https://ci.appveyor.com/project/ChristianSpecht/scm-backup/builds/19444335/artifacts<https://urldefense.proofpoint.com/v2/url?u=https-3A__ci.appveyor.com_project_ChristianSpecht_scm-2Dbackup_builds_19444335_artifacts&d=DwMFaQ&c=UjmJbqZPMTat0o02F6csow&r=WSBk6TzDw3ltxBWUMipVBpFGVfczvxb4hoT-HqEPP-4&m=Fvd7xyTsLmRboRg5--LKirN2QSld6A7STKP34_mVuCE&s=DOxrM1kYIm25Pu0YeW7YgKGtk4dXv3KIg7JOew9JLk0&e=>

**Comment by christianspecht** [comment]
I've moved this to a new issue: #25

**Comment by chrisbwy** [comment]
Hi Christian,

Many thanks for the latest update.

Now the log is ok, no debug stuff in there.

Regards and thanks for your changes here :-)

Chris
